Add fake VCS driver
hound-search/hound pull request #344
Opened 2020-07-09 16:49 UTC by tgulacsi

Add a fake VCS driver, to allow indexing a local, not versioned directory.

2020-10-30 18:24 UTC, salemhilal requested changes
I'm really into this approach! To clarify my understanding:

1. The new driver imports a local directory as a repository by creating a symlink to it
2. The index crawler is updated to follow symlinks
3. A reference hash is approximated by hashing the tar'd output of the directory

If that all sounds good, I think these are the few small things to do before I can merge it:

- [ ] Potentially consider "none" as the config name and the name of the driver.
- [ ] Validate that the driver's initialized with a url that begins with `file://`, and return an error from `newFake()` otherwise. 
- [ ] Add a test file. We don't have any strong integration test patterns yet, but at least validating ^ logic would be a start. It would be extra nice to test the hashing logic as well. I'm also very open to integration test thoughts, if you have any.
- [ ] Add doc blocks and delete that `const fakeSpec` line (I _think_ it isn't used anywhere).

2020-10-30 18:24 UTC, salemhilal commented on vcs/fake.go
> +	cmd.Stdout = hsh
Clever! I really like that this doesn't leave tar files in the filesystem and doesn't (or shouldn't) be a problem with large inputs.

2020-10-30 18:24 UTC, salemhilal commented on vcs/fake.go
> +	src := strings.TrimPrefix(url, "file://")
Is it worth adding a check at initialization time to ensure that the `url` config starts with `file://`?

2020-10-30 18:24 UTC, salemhilal commented on vcs/fake.go
> +const fakeSpec = ".source"
Is this used anywhere?

2020-10-30 18:43 UTC, salemhilal commented
Out of curiosity, are you running into a situation that's preventing a `git init` in a local directory?

2022-08-30 14:40 UTC, mrexodia commented
It would be really great if this could be merged. Is it okay if I take this over? I think `"vcs": "local"` or `"vcs": "file"` would be more descriptive than `none` though.

2022-08-31 09:47 UTC, salemhilal commented
@mrexodia feel free to take this over! I'd also love to know more about your use case for having code search without some sort of version control.

2022-10-11 22:48 UTC, mrexodia commented
Hopefully will be able to get to it this month... My use case is indexing a few GB of leaked source code and adding things to git would take a lot of disk space/time.

2022-10-12 17:34 UTC, salemhilal commented
Hey @mrexodia, I was under the impression that you'd be taking this PR over. Are you able to resolve the outstanding items and comments in this PR?

2022-10-12 18:14 UTC, mrexodia commented
Hopefully eventually, don’t have the most time in the world but I’ll get to it…

2023-06-17 16:06 UTC, closed without merging